name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install Generate RPM
      run:  cargo install cargo-generate-rpm
    - name: Generate RPM
      run: cargo generate-rpm 
    - uses: actions/upload-artifact@v4
      with:
        name: Plugin EGS RPM
        path: target/generate-rpm/*.rpm
        if-no-files-found: error
        retention-days: 90
        compression-level: 0
        overwrite: true
